#define MOUNT_TYPE "ext4"
#include "cmd_ar.c"
#include "cmd_chattr.c"
#include "cmd_dd.c"
#include "cmd_ed.c"
#include "cmd_file.c"
#include "cmd_find.c"
#include "cmd_grep.c"
#include "cmd_gzip.c"
#include "cmd_ls.c"
#include "cmds.c"
#include "cmd_tar.c"
#include "utils.c"
#include "sash.c"
